#!/usr/bin/env python3
"""
Cyber Chaukidaar - Model training & export.

Trains two small models and exports them for BOTH runtimes:

  1. vibration classifier  (Random Forest, 10 features -> NORMAL/HUMAN/VEHICLE/ENVIRONMENT)
  2. intrusion fusion model (Logistic regression over radar + dual-seismic + ML evidence)

Outputs
  ml/models/vibration_rf.json        -> loaded by server/src/ml/classifier.js
  ml/models/fusion_lr.json           -> loaded by server/src/services/fusion.js
  firmware/include/model_vibration.h -> compiled into the ESP32 firmware
  server/src/ml/models/*.json        -> copies for the server

Usage
  python ml/train.py                      # synthetic data only
  python ml/train.py --real data/rec.jsonl  # add real windows logged by the server
  python ml/train.py --trees 10 --depth 6

Real recordings are produced by the server's recorder:
  POST /api/system/record  {"nodeId":"N1","label":"HUMAN","seconds":30}
which writes ml/data/<timestamp>_<label>.jsonl (one window per line:
{"label":"HUMAN","fs":100,"samples":[...]}).

Pure Python - no numpy or scikit-learn needed.
"""

import argparse
import json
import os
import random
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from features import FEATURE_ORDER, FS, extract, as_vector  # noqa: E402
from forest import LogisticRegression, RandomForest  # noqa: E402
from synth import CLASSES, generate  # noqa: E402

ROOT = os.path.dirname(HERE)


# ---------------------------------------------------------------------------
def load_real(paths):
    windows = []
    for p in paths:
        if os.path.isdir(p):
            files = [os.path.join(p, f) for f in os.listdir(p) if f.endswith(".jsonl")]
        else:
            files = [p]
        for fpath in files:
            with open(fpath, "r", encoding="utf-8") as fh:
                for line in fh:
                    line = line.strip()
                    if not line:
                        continue
                    rec = json.loads(line)
                    label = rec.get("label", "").upper()
                    if label not in CLASSES:
                        continue
                    samples = rec.get("samples") or []
                    if len(samples) < 32:
                        continue
                    windows.append((samples, CLASSES.index(label)))
    return windows


def confusion(model, X, y, n_classes):
    m = [[0] * n_classes for _ in range(n_classes)]
    for x, t in zip(X, y):
        m[t][model.predict(x)] += 1
    return m


def print_confusion(m, names):
    w = max(len(n) for n in names) + 2
    print(" " * w + "".join(n[:7].rjust(8) for n in names))
    for i, row in enumerate(m):
        print(names[i].ljust(w) + "".join(str(v).rjust(8) for v in row))
    correct = sum(m[i][i] for i in range(len(names)))
    total = sum(sum(r) for r in m)
    print(f"accuracy: {correct}/{total} = {100.0 * correct / max(1, total):.1f}%")


# ---------------------------------------------------------------------------
def export_c_header(forest_dict, path):
    """Flatten forest into compact arrays for the ESP32 (no recursion, no malloc)."""
    nodes = []  # each: (feature, threshold, left, right, probs or None)
    tree_roots = []

    def flatten(node):
        my = len(nodes)
        nodes.append(None)
        if "p" in node:
            nodes[my] = (-1, 0.0, -1, -1, node["p"])
            return my
        l = flatten(node["l"])
        r = flatten(node["r"])
        nodes[my] = (node["f"], node["t"], l, r, None)
        return my

    for t in forest_dict["trees"]:
        tree_roots.append(flatten(t))

    n_classes = len(forest_dict["classes"])
    lines = []
    lines.append("// AUTO-GENERATED by ml/train.py - do not edit by hand.")
    lines.append("// Random Forest vibration classifier for the Cyber Chaukidaar sentry node.")
    lines.append(f"// Generated {time.strftime('%Y-%m-%d %H:%M:%S')}  trees={len(tree_roots)} nodes={len(nodes)}")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define ML_NUM_FEATURES {len(forest_dict['features'])}")
    lines.append(f"#define ML_NUM_CLASSES {n_classes}")
    lines.append(f"#define ML_NUM_TREES {len(tree_roots)}")
    lines.append(f"#define ML_NUM_NODES {len(nodes)}")
    lines.append("")
    lines.append("static const char* const ML_CLASS_NAMES[ML_NUM_CLASSES] = {")
    lines.append("    " + ", ".join(f'"{c}"' for c in forest_dict["classes"]))
    lines.append("};")
    lines.append("")
    lines.append("// Feature order: " + ", ".join(forest_dict["features"]))
    lines.append("")
    lines.append("struct MlNode { int8_t feature; float threshold; int16_t left; int16_t right; int16_t leaf; };")
    lines.append("")
    leaves = [n for n in nodes if n[4] is not None]
    leaf_index = {}
    lines.append("static const float ML_LEAF_PROBS[][ML_NUM_CLASSES] = {")
    for i, n in enumerate(leaves):
        leaf_index[id(n)] = i
        lines.append("    {" + ", ".join(f"{p:.4f}f" for p in n[4]) + "},")
    lines.append("};")
    lines.append("")
    lines.append("static const MlNode ML_NODES[ML_NUM_NODES] = {")
    for n in nodes:
        if n[4] is not None:
            lines.append(f"    {{-1, 0.0f, -1, -1, {leaf_index[id(n)]}}},")
        else:
            lines.append(f"    {{{n[0]}, {n[1]:.6f}f, {n[2]}, {n[3]}, -1}},")
    lines.append("};")
    lines.append("")
    lines.append("static const int16_t ML_TREE_ROOTS[ML_NUM_TREES] = {" + ", ".join(str(r) for r in tree_roots) + "};")
    lines.append("")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    return len(nodes)


# ---------------------------------------------------------------------------
FUSION_FEATURES = [
    "radarPresence",     # 0/1
    "radarDistanceNorm", # 0..1 (distance / 8m), 1 when absent
    "radarEnergy",       # 0..1
    "s1Rms",             # g
    "s2Rms",             # g
    "dualCorroboration", # 0/1 both probes above their noise floor
    "seismicCorr",       # 0..1 cross-correlation peak between probes
    "pHuman",            # RF probability
    "pVehicle",
    "pEnvironment",
]


def synth_fusion_dataset(n=6000, seed=3):
    """Scenario generator: emits evidence vectors + ground-truth intrusion flag."""
    rng = random.Random(seed)
    X, y = [], []
    for _ in range(n):
        scenario = rng.random()
        if scenario < 0.35:
            # quiet: nothing there
            radar = 1 if rng.random() < 0.03 else 0        # rare radar false positive
            dist = rng.uniform(0.2, 1.0) if radar else 1.0
            eng = rng.uniform(0.1, 0.5) if radar else rng.uniform(0, 0.1)
            s1 = abs(rng.gauss(0.012, 0.006))
            s2 = abs(rng.gauss(0.012, 0.006))
            dual = 0
            corr = rng.uniform(0.0, 0.3)
            ph, pv, pe = rng.uniform(0, 0.15), rng.uniform(0, 0.1), rng.uniform(0, 0.2)
            label = 0
        elif scenario < 0.55:
            # environmental disturbance (wind/rain) - should NOT alarm
            radar = 1 if rng.random() < 0.06 else 0
            dist = rng.uniform(0.3, 1.0) if radar else 1.0
            eng = rng.uniform(0.1, 0.4) if radar else rng.uniform(0, 0.1)
            s1 = abs(rng.gauss(0.08, 0.05))
            s2 = abs(rng.gauss(0.08, 0.05))
            dual = 1 if (s1 > 0.03 and s2 > 0.03) else 0
            corr = rng.uniform(0.2, 0.7)
            pe = rng.uniform(0.5, 0.95)
            ph = rng.uniform(0, 0.3) * (1 - pe)
            pv = rng.uniform(0, 0.3) * (1 - pe)
            label = 0
        elif scenario < 0.85:
            # human intrusion
            radar = 1 if rng.random() < 0.85 else 0         # radar sometimes misses (crouching/behind cover)
            dist = rng.uniform(0.1, 1.0) if radar else 1.0
            eng = rng.uniform(0.35, 1.0) if radar else rng.uniform(0, 0.1)
            base = rng.uniform(0.04, 0.5)
            s1 = base * rng.uniform(0.6, 1.4)
            s2 = base * rng.uniform(0.6, 1.4)
            dual = 1 if (s1 > 0.03 and s2 > 0.03) else 0
            corr = rng.uniform(0.45, 0.95)
            ph = rng.uniform(0.55, 0.98)
            pv = rng.uniform(0, 0.2) * (1 - ph)
            pe = rng.uniform(0, 0.3) * (1 - ph)
            label = 1
        else:
            # vehicle
            radar = 1 if rng.random() < 0.7 else 0
            dist = rng.uniform(0.3, 1.0) if radar else 1.0
            eng = rng.uniform(0.3, 1.0) if radar else rng.uniform(0, 0.1)
            base = rng.uniform(0.1, 0.8)
            s1 = base * rng.uniform(0.7, 1.3)
            s2 = base * rng.uniform(0.7, 1.3)
            dual = 1
            corr = rng.uniform(0.6, 0.98)
            pv = rng.uniform(0.55, 0.98)
            ph = rng.uniform(0, 0.2) * (1 - pv)
            pe = rng.uniform(0, 0.2) * (1 - pv)
            label = 1
        X.append([radar, dist, eng, s1, s2, dual, corr, ph, pv, pe])
        y.append(label)
    return X, y


# ---------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--real", nargs="*", default=[], help="jsonl files/dirs with real labelled windows")
    ap.add_argument("--per-class", type=int, default=450)
    ap.add_argument("--trees", type=int, default=8)
    ap.add_argument("--depth", type=int, default=6)
    ap.add_argument("--min-leaf", type=int, default=4)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--out", default=os.path.join(HERE, "models"))
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)
    t0 = time.time()

    print(f"[1/5] generating synthetic windows ({args.per_class}/class @ {FS:.0f} Hz)...")
    windows = generate(per_class=args.per_class, seed=args.seed)
    real = load_real(args.real) if args.real else []
    if real:
        print(f"      + {len(real)} real labelled windows")
        # real data is worth more: duplicate it 3x
        windows.extend(real * 3)
        random.Random(args.seed).shuffle(windows)

    print("[2/5] extracting features...")
    X = [as_vector(extract(w)) for w, _ in windows]
    y = [lbl for _, lbl in windows]

    n_test = max(1, len(X) // 5)
    X_test, y_test = X[:n_test], y[:n_test]
    X_train, y_train = X[n_test:], y[n_test:]

    print(f"[3/5] training random forest (trees={args.trees}, depth={args.depth}) on {len(X_train)} windows...")
    rf = RandomForest(n_trees=args.trees, max_depth=args.depth, min_leaf=args.min_leaf, seed=args.seed)
    rf.fit(X_train, y_train)
    print("      test-set confusion matrix:")
    print_confusion(confusion(rf, X_test, y_test, len(CLASSES)), CLASSES)
    print(f"      forest size: {rf.node_count()} nodes")

    rf_dict = rf.to_dict(FEATURE_ORDER, CLASSES)
    rf_dict["meta"] = {
        "trainedAt": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "windows": len(X_train),
        "realWindows": len(real),
        "fs": FS,
        "version": "2.0.0",
    }

    print("[4/5] training fusion logistic regression...")
    FX, FY = synth_fusion_dataset()
    lr = LogisticRegression(lr=0.05, epochs=120, l2=1e-4, seed=args.seed).fit(FX, FY)
    tp = fp = tn = fn = 0
    for x, t in zip(FX, FY):
        p = lr.predict_proba(x) >= 0.5
        if p and t:
            tp += 1
        elif p and not t:
            fp += 1
        elif not p and t:
            fn += 1
        else:
            tn += 1
    print(f"      fusion train acc={(tp + tn) / len(FX) * 100:.1f}%  precision={tp / max(1, tp + fp):.2f} recall={tp / max(1, tp + fn):.2f}")
    lr_dict = lr.to_dict(FUSION_FEATURES)
    lr_dict["meta"] = {"trainedAt": rf_dict["meta"]["trainedAt"], "version": "2.0.0"}

    print("[5/5] exporting...")
    rf_path = os.path.join(args.out, "vibration_rf.json")
    lr_path = os.path.join(args.out, "fusion_lr.json")
    with open(rf_path, "w", encoding="utf-8") as fh:
        json.dump(rf_dict, fh, indent=1)
    with open(lr_path, "w", encoding="utf-8") as fh:
        json.dump(lr_dict, fh, indent=1)

    server_models = os.path.join(ROOT, "server", "src", "ml", "models")
    os.makedirs(server_models, exist_ok=True)
    for src in (rf_path, lr_path):
        with open(src, "r", encoding="utf-8") as fh:
            data = fh.read()
        with open(os.path.join(server_models, os.path.basename(src)), "w", encoding="utf-8") as fh:
            fh.write(data)

    header = os.path.join(ROOT, "firmware", "include", "model_vibration.h")
    os.makedirs(os.path.dirname(header), exist_ok=True)
    n_nodes = export_c_header(rf_dict, header)

    print(f"      {rf_path}")
    print(f"      {lr_path}")
    print(f"      {header}  ({n_nodes} nodes, ~{n_nodes * 12 / 1024:.1f} KB flash)")
    print(f"done in {time.time() - t0:.1f}s")


if __name__ == "__main__":
    main()
